spring:
  application:
    name: Address-service
  datasource:
    password: Amine1998@@
    username: root
    url: jdbc:mysql://localhost:3303/MicroS
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true
        jdbc.time_zone: UTC
#        dialect: org.hibernate.dialect.MySQLDialect
        types.print.banner: false
        format_sql: true

server:
  port: 8091
  servlet:
    contextPath: ${CONTEXT_PATH:/api}
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
